spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/person_db
    username: postgres
    password: 4639a1597
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create